services:
  mongo:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  register-service:
    build: ./register-service
    container_name: register-service
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/merndb
  
  login-service:
    build: ./login-service
    container_name: login-service
    restart: always
    ports:
      - "4002:4002"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/merndb
      

  token-service:
    build: ./token-service
    container_name: token-service
    restart: always
    ports:
      - "4001:4001"
    depends_on:
      - register-service
    environment:
      - TOKEN_SECRET=uce2025

  # 🔹 Nuevo servicio para ver MongoDB desde el navegador
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin

volumes:
  mongo_data:
